# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd353faf9141f4b85ee5766e86f95ad8bc8052f708c4acbe07b1bea08718dcf4d7be8b913123cb4a92252cc2834f8b9f3c3150b203b2456d1ec160f6299fc3e5

test:
  secret_key_base: 19e1dc4c8edd74e9a0bd00fbd3ea7b7062e1c20fe853a7796a5d0e40f1e134602f1f995c0b7e7c8cb5ffcc0bb936cb316b7dc956025034a867b248d40e3eead5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
